#pragma once

#define VIAL_KEYBOARD_UID {0x32, 0xD9, 0x5A, 0x29, 0x4B, 0x99, 0x79, 0xC8}

#undef VENDOR_ID
#define VENDOR_ID 0x4450

#undef MANUFACTURER
#define MANUFACTURER DKN

#define USE_SERIAL
#define EE_HANDS

#define COMBO_TERM 20

#define RGBLED_NUM_PER_HALF 35
#undef RGBLED_NUM
#define RGBLED_NUM RGBLED_NUM_PER_HALF*2
#define RGBLED_SPLIT { RGBLED_NUM_PER_HALF, RGBLED_NUM_PER_HALF}
// #define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL 180

// turn things off to save space
#undef NO_ACTION_ONESHOT
#define NO_ACTION_ONESHOT
#undef NO_ACTION_MACRO